/**
 * Serving the photos that uploads.routes.ts writes.
 *
 * `POST /people/:id/photo` stored a file and returned `/uploads/<uuid>.jpg`, and
 * **nothing served that path** — not in development, where Vite proxies
 * `/uploads` straight here, and not in production, where nginx does the same.
 * Every photo anyone uploaded came back a 404. `@fastify/static` was in
 * package.json for this and was never registered.
 *
 * This is deliberately not `@fastify/static`. That package exists to serve a
 * whole directory tree with directory listings, dotfile rules and encoded-path
 * handling — and four path-traversal advisories were open against it at the
 * version this project had. None of that surface is wanted here: exactly one
 * shape of filename is ever served, it was generated by this server, and the
 * name is checked against a pattern before it is used at all.
 *
 * Registered at the root, not under /api/v1, because that is the URL already
 * stored in every `person.photo` and already proxied by nginx.
 */

import { createReadStream } from 'node:fs';
import { stat } from 'node:fs/promises';
import path from 'node:path';
import type { FastifyInstance } from 'fastify';
import fp from 'fastify-plugin';

/** A UUID and one of the three extensions the uploader can produce. Nothing else. */
const NAME = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$/;

const TYPES: Record<string, string> = {
  jpg: 'image/jpeg',
  png: 'image/png',
  webp: 'image/webp',
};

async function plugin(app: FastifyInstance) {
  const root = path.resolve(app.env.UPLOAD_DIR);

  app.get<{ Params: { name: string } }>(
    '/uploads/:name',
    { schema: { hide: true } },
    async (req, reply) => {
      const { name } = req.params;

      // The pattern already excludes `..`, slashes and every encoding of them,
      // because it admits nothing but hex, four hyphens and a known extension.
      if (!NAME.test(name)) return reply.status(404).send({ error: 'Not found.' });

      const file = path.join(root, name);
      // Belt and braces: if anything above ever loosens, this still refuses a
      // path that escaped the upload directory.
      if (path.dirname(file) !== root) return reply.status(404).send({ error: 'Not found.' });

      try {
        const info = await stat(file);
        if (!info.isFile()) return reply.status(404).send({ error: 'Not found.' });

        const ext = name.slice(name.lastIndexOf('.') + 1);
        return (
          reply
            .type(TYPES[ext] ?? 'application/octet-stream')
            .header('content-length', String(info.size))
            // The name contains a UUID, so a given URL is always the same bytes.
            .header('cache-control', 'public, max-age=604800, immutable')
            .header('x-content-type-options', 'nosniff')
            .send(createReadStream(file))
        );
      } catch {
        return reply.status(404).send({ error: 'Not found.' });
      }
    },
  );
}

export const serveUploadsPlugin = fp(plugin, { name: 'serve-uploads' });
