/**
 * Seed data, lifted verbatim from the single-file build so the database starts
 * out identical to what the client has already reviewed and signed off on.
 *
 * `buildRoster` is deterministic: the same seed integer always produces the same
 * 181 people, with the same names, dates and reporting lines. Re-seeding a fresh
 * database twice gives byte-identical rows, which is what makes a seeded
 * environment something you can write a test against.
 */

/* eslint-disable */

export const FIRST_M = [
  'Amrit',
  'Baldev',
  'Charanjit',
  'Davinder',
  'Gurpreet',
  'Harjeet',
  'Inderjit',
  'Jaswinder',
  'Kuldeep',
  'Lakhvir',
  'Manpreet',
  'Narinder',
  'Onkar',
  'Paramjit',
  'Rajinder',
  'Sukhwinder',
  'Tarlochan',
  'Varinder',
  'Yadwinder',
  'Ashok',
  'Bhupinder',
  'Chetan',
  'Dinesh',
  'Gagandeep',
  'Hardeep',
  'Jagdish',
  'Karan',
  'Mohan',
  'Naveen',
  'Pankaj',
  'Rakesh',
  'Sandeep',
  'Tarun',
  'Vikram',
  'Yogesh',
  'Amit',
  'Bharat',
  'Deepak',
  'Gurmeet',
  'Hemant',
  'Jatinder',
  'Kamal',
  'Mukesh',
  'Nitin',
  'Prem',
  'Ravi',
  'Sunil',
  'Umesh',
  'Vinod',
  'Ramesh',
];

export const FIRST_F = [
  'Amandeep',
  'Baljit',
  'Charanjeet',
  'Daljit',
  'Gurmeet',
  'Harpreet',
  'Inderpreet',
  'Jaspreet',
  'Kamaljit',
  'Lakhwinder',
  'Manjit',
  'Navjot',
  'Parminder',
  'Rajwinder',
  'Simran',
  'Sukhjit',
  'Tejinder',
  'Veerpal',
  'Anita',
  'Bhavna',
  'Chetna',
  'Divya',
  'Geeta',
  'Heena',
  'Jyoti',
  'Kavita',
  'Meena',
  'Neha',
  'Pooja',
  'Radha',
  'Sunita',
  'Usha',
  'Vandana',
  'Anjali',
  'Bindu',
  'Deepika',
  'Gurleen',
  'Kiran',
  'Mamta',
  'Nisha',
  'Priya',
  'Ritu',
  'Shalini',
  'Tanvi',
];

export const SURN = [
  'Singh',
  'Kaur',
  'Sharma',
  'Verma',
  'Gupta',
  'Chauhan',
  'Yadav',
  'Kumar',
  'Rana',
  'Thakur',
  'Bansal',
  'Goyal',
  'Mehta',
  'Malhotra',
  'Sethi',
  'Nair',
  'Iyer',
  'Bhatia',
  'Sidhu',
  'Gill',
  'Dhillon',
  'Grewal',
  'Sandhu',
  'Brar',
  'Sekhon',
  'Walia',
  'Khanna',
  'Kapoor',
  'Chopra',
  'Arora',
  'Saini',
  'Joshi',
  'Tiwari',
  'Mishra',
  'Pandey',
  'Prasad',
  'Devi',
  'Lal',
  'Ram',
  'Das',
];

export const OFFICE_IDS = ['hq', 'grand', 'twin', 'curo', 'royce'];

export const ROLES: Record<string, Array<[string, number]>> = {
  'Site Engineering': [
    ['Site Engineer', 6],
    ['Site Supervisor', 8],
    ['Junior Engineer', 5],
    ['Surveyor', 3],
    ['Project Engineer', 3],
    ['Site Manager', 2],
  ],
  Security: [
    ['Gate Security', 14],
    ['Security Supervisor', 3],
    ['Club House Guard', 6],
    ['Night Guard', 5],
    ['Security In-charge', 1],
  ],
  Labour: [
    ['Bar-bender', 8],
    ['Mason', 9],
    ['Carpenter', 7],
    ['Helper', 8],
    ['Painter', 4],
    ['Plumber Helper', 4],
    ['Electrician Helper', 4],
  ],
  Store: [
    ['Store Assistant', 7],
    ['Store Keeper', 4],
    ['Store Supervisor', 2],
    ['Material Checker', 3],
  ],
  Purchase: [
    ['Purchase Assistant', 4],
    ['Purchase Executive', 3],
    ['Buyer', 2],
  ],
  Accounts: [
    ['Accounts Assistant', 4],
    ['Accountant', 3],
    ['Billing Executive', 2],
  ],
  Maintenance: [
    ['Maintenance Technician', 5],
    ['Electrician', 4],
    ['Plumber', 3],
    ['AC Technician', 2],
    ['Lift Technician', 1],
  ],
  'QA / QC': [
    ['QA / QC Engineer', 3],
    ['Lab Technician', 2],
    ['Quality Inspector', 2],
  ],
  HR: [
    ['HR Executive', 2],
    ['HR Assistant', 2],
    ['Payroll Executive', 1],
  ],
  Marketing: [
    ['Marketing Executive', 3],
    ['Digital Marketing Executive', 2],
    ['CRM Executive', 2],
    ['Graphic Designer', 1],
  ],
  Admin: [
    ['Club House Manager', 2],
    ['Fitness Trainer', 3],
    ['House Keeping Supervisor', 3],
    ['Receptionist', 3],
    ['Front Office Executive', 2],
    ['Office Assistant', 3],
    ['Driver', 4],
  ],
};

export const ORG_SEED: any = {
  'MB-ADM-0001': { boss: null, office: 'hq' },
  'MB-HR-0001': { boss: 'MB-ADM-0001', office: 'hq' },
  'MB-MKT-0001': { boss: 'MB-ADM-0001', office: 'hq' },
  'MB-PUR-0012': { boss: 'MB-ADM-0001', office: 'hq' },
  'MB-STR-0004': { boss: 'MB-ADM-0001', office: 'grand' },
  'MB-ACC-0002': { boss: 'MB-ADM-0001', office: 'hq' },
  'MB-MNT-0006': { boss: 'MB-ADM-0001', office: 'grand' },
  'MB-PUR-0018': { boss: 'MB-PUR-0012', office: 'hq' },
  'MB-STR-0009': { boss: 'MB-STR-0004', office: 'grand' },
  'MB-SIT-0021': { boss: 'MB-ADM-0001', office: 'twin' },
  'MB-SEC-0007': { boss: 'MB-HR-0001', office: 'grand' },
  'MB-SEC-0012': { boss: 'MB-HR-0001', office: 'twin' },
  'MB-SIT-0052': { boss: 'MB-SIT-0021', office: 'curo' },
  'MB-STR-0014': { boss: 'MB-STR-0004', office: 'grand' },
  'MB-PUR-0009': { boss: 'MB-PUR-0012', office: 'hq' },
  'MB-LAB-0087': { boss: 'MB-SIT-0021', office: 'grand' },
  'MB-LAB-0102': { boss: 'MB-SIT-0021', office: 'grand' },
  'MB-LAB-0118': { boss: 'MB-SIT-0021', office: 'twin' },
  'MB-LAB-0131': { boss: 'MB-SIT-0052', office: 'curo' },
  'MB-SIT-0044': { boss: 'MB-SIT-0021', office: 'twin' },
};

export const EMPLOYER_SEED: any = {
  'MB-ADM-0001': 'dpre',
  'MB-HR-0001': 'dpre',
  'MB-PUR-0012': 'dpre',
  'MB-STR-0004': 'dpre',
  'MB-ACC-0002': 'dpre',
  'MB-MNT-0006': 'dpre',
  'MB-PUR-0018': 'dpre',
  'MB-STR-0009': 'dpre',
  'MB-SIT-0021': 'dpre',
  'MB-SIT-0044': 'dpre',
  'MB-SIT-0052': 'drdc',
  'MB-STR-0014': 'dpre',
  'MB-SEC-0007': 'srg',
  'MB-SEC-0012': 'srg',
  'MB-PUR-0009': 'dpre',
  'MB-LAB-0087': 'srg',
  'MB-LAB-0102': 'srg',
  'MB-LAB-0118': 'srg',
  'MB-LAB-0131': 'drdc',
};

export const PEOPLE_SEED: any = [
  {
    id: 'MB-MKT-0001',
    name: 'Meera Anand',
    designation: 'Marketing Head',
    dept: 'Marketing',
    type: 'Staff',
    phone: '+91 98140 00031',
    email: 'meera@marbellagroup.in',
    joined: '05 Apr 2023',
    status: 'active',
    perf: 88,
    growth: 'Runs the sample flat and the channel partners.',
    notes: [],
  },
  {
    id: 'MB-ADM-0001',
    name: 'Nitish Walia',
    designation: 'Chairman',
    dept: 'Admin',
    type: 'Staff',
    phone: '+91 98140 00001',
    email: 'nitish@marbellagroup.in',
    joined: '02 Jan 2019',
    status: 'active',
    perf: 100,
    growth: 'Founder — sets the standard.',
    notes: [],
  },
  {
    id: 'MB-HR-0001',
    name: 'Simran Kaur',
    designation: 'HR Head',
    dept: 'HR',
    type: 'Staff',
    phone: '+91 98140 00021',
    email: 'simran@marbellagroup.in',
    joined: '10 Feb 2021',
    status: 'active',
    perf: 96,
    growth: 'Runs the people function end-to-end.',
    notes: [],
  },
  {
    id: 'MB-PUR-0012',
    name: 'R. Khanna',
    designation: 'Purchase Manager',
    dept: 'Purchase',
    type: 'Staff',
    phone: '+91 98140 00012',
    email: 'khanna@marbellagroup.in',
    joined: '14 Mar 2020',
    status: 'active',
    perf: 94,
    growth: 'Ready for a Sr. Manager conversation next review.',
    notes: [
      { when: '2 weeks ago', text: 'Negotiated 6% off steel — flag for appreciation letter.' },
    ],
  },
  {
    id: 'MB-STR-0004',
    name: 'S. Verma',
    designation: 'Store Manager',
    dept: 'Store',
    type: 'Staff',
    phone: '+91 98140 00040',
    email: 'verma@marbellagroup.in',
    joined: '05 Jun 2020',
    status: 'active',
    perf: 88,
    growth: 'Solid. Needs delegation coaching.',
    notes: [],
  },
  {
    id: 'MB-ACC-0002',
    name: 'P. Nair',
    designation: 'Accounts Head',
    dept: 'Accounts',
    type: 'Staff',
    phone: '+91 98140 00002',
    email: 'nair@marbellagroup.in',
    joined: '20 Aug 2019',
    status: 'active',
    perf: 97,
    growth: 'Dependable. Backbone of reconciliation.',
    notes: [],
  },
  {
    id: 'MB-MNT-0006',
    name: 'M. Chauhan',
    designation: 'Maintenance Lead',
    dept: 'Maintenance',
    type: 'Staff',
    phone: '+91 98140 00060',
    email: 'chauhan@marbellagroup.in',
    joined: '11 Jan 2021',
    status: 'active',
    perf: 82,
    growth: 'Strong on-site; paperwork lags.',
    notes: [],
  },
  {
    id: 'MB-PUR-0018',
    name: 'A. Sethi',
    designation: 'Purchase Assistant',
    dept: 'Purchase',
    type: 'Staff',
    phone: '+91 98140 00018',
    email: 'sethi@marbellagroup.in',
    joined: '03 Sep 2023',
    status: 'active',
    perf: 71,
    growth: 'Quality dipped this quarter — watch & support.',
    notes: [{ when: '1 week ago', text: 'Two invoices mismatched. Scheduled a sit-down.' }],
  },
  {
    id: 'MB-STR-0009',
    name: 'D. Rana',
    designation: 'Store Assistant',
    dept: 'Store',
    type: 'Staff',
    phone: '+91 98140 00090',
    email: 'rana@marbellagroup.in',
    joined: '18 Nov 2023',
    status: 'active',
    perf: 63,
    growth: 'New-ish. Improving month on month.',
    notes: [],
  },
  {
    id: 'MB-SIT-0021',
    name: 'K. Iyer',
    designation: 'Site Engineer',
    dept: 'Site Engineering',
    type: 'Site',
    phone: '+91 98140 00210',
    email: 'iyer@marbellagroup.in',
    joined: '12 Apr 2022',
    status: 'active',
    perf: 90,
    growth: 'Promotable to Sr. Site Engineer.',
    notes: [],
  },
  {
    id: 'MB-SIT-0044',
    name: 'Ramesh Yadav',
    designation: 'Site Supervisor',
    dept: 'Site Engineering',
    type: 'Site',
    phone: '+91 98140 00440',
    email: '',
    joined: '07 Jul 2022',
    status: 'active',
    perf: 85,
    growth: 'Reliable on Twin Towers.',
    notes: [],
  },
  {
    id: 'MB-SIT-0052',
    name: 'Priya Sharma',
    designation: 'QA / QC Engineer',
    dept: 'QA / QC',
    type: 'Site',
    phone: '+91 98140 00520',
    email: 'priya@marbellagroup.in',
    joined: '22 Feb 2023',
    status: 'active',
    perf: 91,
    growth: 'Sharp eye. Give her a mentee.',
    notes: [],
  },
  {
    id: 'MB-STR-0014',
    name: 'Naveen Kumar',
    designation: 'Store Keeper',
    dept: 'Store',
    type: 'Staff',
    phone: '+91 98140 00140',
    email: '',
    joined: '09 May 2023',
    status: 'active',
    perf: 78,
    growth: 'Steady.',
    notes: [],
  },
  {
    id: 'MB-SEC-0007',
    name: 'Gurpreet Singh',
    designation: 'Security Guard',
    dept: 'Security',
    type: 'Security',
    phone: '+91 98140 00070',
    email: '',
    joined: '15 Oct 2022',
    status: 'active',
    perf: 80,
    growth: 'Punctual, alert.',
    notes: [],
  },
  {
    id: 'MB-SEC-0012',
    name: 'Manoj Kumar',
    designation: 'Gate Security',
    dept: 'Security',
    type: 'Security',
    phone: '+91 98140 00120',
    email: '',
    joined: '01 Dec 2023',
    status: 'active',
    perf: 74,
    growth: 'New. On probation review.',
    notes: [],
  },
  {
    id: 'MB-LAB-0102',
    name: 'Bhola Prasad',
    designation: 'Mason',
    dept: 'Labour',
    type: 'Labour',
    phone: '+91 98140 01020',
    email: '',
    joined: '03 Mar 2024',
    status: 'active',
    perf: 86,
    growth: 'Skilled mason — retain.',
    notes: [],
  },
  {
    id: 'MB-LAB-0118',
    name: 'Suresh Kumar',
    designation: 'Bar-bender',
    dept: 'Labour',
    type: 'Labour',
    phone: '+91 98140 01180',
    email: '',
    joined: '03 Mar 2024',
    status: 'active',
    perf: 82,
    growth: 'Good output.',
    notes: [],
  },
  {
    id: 'MB-LAB-0131',
    name: 'Lakhan Singh',
    designation: 'Helper',
    dept: 'Labour',
    type: 'Labour',
    phone: '+91 98140 01310',
    email: '',
    joined: '19 Apr 2024',
    status: 'active',
    perf: 70,
    growth: 'Learning fast.',
    notes: [],
  },
  {
    id: 'MB-PUR-0009',
    name: 'Vikram Malhotra',
    designation: 'Purchase Executive',
    dept: 'Purchase',
    type: 'Staff',
    phone: '+91 98140 00009',
    email: '',
    joined: '06 Jun 2021',
    status: 'exited',
    exitedOn: '12 Mar 2025',
    perf: 0,
    growth: 'Left the group. Access revoked.',
    notes: [
      {
        when: '12 Mar 2025',
        text: "Exit processed. Card deactivated — any card he shares now must read 'not with Marbella'.",
      },
    ],
  },
  {
    id: 'MB-LAB-0087',
    name: 'Ram Avtar',
    designation: 'Helper',
    dept: 'Labour',
    type: 'Labour',
    phone: '',
    email: '',
    joined: '10 Jan 2024',
    status: 'exited',
    exitedOn: '28 Feb 2025',
    perf: 0,
    growth: 'Season ended.',
    notes: [],
  },
];

export const OFFICES: any = [
  { id: 'hq', name: 'Head Office · Sector 22-C', short: 'Head Office', tint: '#224A85' },
  { id: 'grand', name: 'Marbella Grand · Site Office', short: 'Grand', tint: '#3E7C55' },
  { id: 'twin', name: 'Twin Towers · Site Office', short: 'Twin Towers', tint: '#8A6224' },
  { id: 'curo', name: 'Curo One · Site Office', short: 'Curo One', tint: '#7B4B8A' },
  { id: 'royce', name: 'Royce · Site Office', short: 'Royce', tint: '#B0503C' },
];

export const COMPANY_SEED: any = [
  {
    id: 'dpre',
    name: 'Delhi Punjab Real Estates LLP',
    gstin: '03AAEFD4921K1Z9',
    pan: 'AAEFD4921K',
    kind: 'LLP',
    addr: 'SCO 2417-18, Sector 22-C, Chandigarh 160022',
  },
  {
    id: 'drdc',
    name: 'D.R. Developers & Colonisers',
    gstin: '03AAKFD3356N1ZB',
    pan: 'AAKFD3356N',
    kind: 'Partnership',
    addr: 'SCO 2417-18, Sector 22-C, Chandigarh 160022',
  },
  {
    id: 'desraj',
    name: 'Des Raj Real Estates Pvt. Ltd.',
    gstin: '03AABCD7890P1ZR',
    pan: 'AABCD7890P',
    kind: 'Private Limited',
    addr: 'SCO 2417-18, Sector 22-C, Chandigarh 160022',
  },
  {
    id: 'srg',
    name: 'SRG Developers and Promoters',
    gstin: '',
    pan: '',
    kind: 'Partnership',
    addr: 'SCO 2417-18, Sector 22-C, Chandigarh 160022',
  },
];

export const PROJECT_SEED: any = [
  {
    id: 'grand',
    name: 'Marbella Grand',
    short: 'Grand',
    company: 'dpre',
    reraStatus: 'received',
    rera: 'PBRERA-SAS79-PR0421',
    stage: 'building',
    addr: 'GHS 3, Sector 82-A, IT City Road, Sector 82, S.A.S. Nagar, Punjab 140306',
  },
  {
    id: 'twin',
    name: 'Twin Towers',
    short: 'Twin Towers',
    company: 'dpre',
    reraStatus: 'received',
    rera: 'PBRERA-SAS79-PR0512',
    stage: 'building',
    addr: '1st LOT, Main Road Sector 2, Madhya Marg, DLF Mullanpur, New Chandigarh, Punjab 140901',
  },
  {
    id: 'curo',
    name: 'Marbella Curo One',
    short: 'Curo One',
    company: 'drdc',
    reraStatus: 'received',
    rera: 'PBRERA-SAS79-PR0338',
    stage: 'building',
    addr: '1st LOT, Main Road Sector 2, Madhya Marg, DLF Mullanpur, New Chandigarh, Punjab 140901',
  },
  {
    id: 'royce',
    name: 'Marbella Royce',
    short: 'Royce',
    company: 'drdc',
    reraStatus: 'received',
    rera: 'PBRERA-SAS79-PR0445',
    stage: 'building',
    addr: 'Site No. 7, Block C, Sector 83-A, IT City Road, S.A.S. Nagar, Punjab 140306',
  },
  {
    id: 'manifest',
    name: 'Marbella Manifest',
    short: 'Manifest',
    company: 'desraj',
    reraStatus: 'applied',
    rera: '',
    stage: 'pre',
    addr: 'SCO 2417-18, Sector 22-C, Chandigarh 160022',
  },
];

export const CARD_LOG_SEED: any = [
  {
    id: 'CD-1041',
    pid: 'MB-SEC-0007',
    name: 'Gurpreet Singh',
    ver: 2,
    reason: 'damaged',
    at: '18 Jul 2026 · 10:12',
    by: 'Simran Kaur',
    recv: 'Simran Kaur',
    note: 'Edge delaminated after monsoon. Old card destroyed in front of holder.',
    killed: 'CD-0902',
  },
  {
    id: 'CD-1038',
    pid: 'MB-PUR-0018',
    name: 'A. Sethi',
    ver: 2,
    reason: 'lost',
    at: '02 Jul 2026 · 16:40',
    by: 'Simran Kaur',
    recv: '—',
    note: 'Left in a shared auto between Sector 22 and site. Retraced route, not found. Manager R. Khanna informed same evening.',
    killed: 'CD-0781',
    zonesKilled: true,
  },
  {
    id: 'CD-1035',
    pid: 'MB-STR-0009',
    name: 'D. Rana',
    ver: 1,
    reason: 'first',
    at: '21 Jun 2026 · 09:05',
    by: 'Simran Kaur',
    recv: '—',
    note: 'New joiner.',
  },
  {
    id: 'CD-1030',
    pid: 'MB-MNT-0006',
    name: 'M. Chauhan',
    ver: 1,
    reason: 'first',
    at: '11 Jun 2026 · 11:30',
    by: 'Simran Kaur',
    recv: '—',
    note: 'New joiner.',
  },
];

export const DEPT_RULES_SEED: any = {
  Marketing: {
    in: '10:00',
    out: '19:00',
    hours: 8,
    days: 'Wed–Mon',
    grace: 15,
    setBy: 'Meera Anand',
    note: 'Site visits are Saturday and Sunday. Tuesday is the weekly off.',
  },
  Purchase: {
    in: '09:30',
    out: '18:30',
    hours: 8,
    days: 'Mon–Sat',
    grace: 15,
    setBy: 'R. Khanna',
    note: 'Half day Saturday from 2pm.',
  },
  Store: {
    in: '08:00',
    out: '18:00',
    hours: 9,
    days: 'Mon–Sat',
    grace: 10,
    setBy: 'S. Verma',
    note: 'Store opens before site starts.',
  },
  Maintenance: {
    in: '07:00',
    out: '16:00',
    hours: 8,
    days: 'Mon–Sat',
    grace: 10,
    setBy: 'M. Chauhan',
    note: 'Early start for plant checks.',
  },
  Accounts: {
    in: '10:00',
    out: '19:00',
    hours: 8,
    days: 'Mon–Fri',
    grace: 15,
    setBy: 'P. Nair',
    note: '',
  },
  'Site Engineering': {
    in: '07:30',
    out: '17:30',
    hours: 9,
    days: 'Mon–Sat',
    grace: 10,
    setBy: 'K. Iyer',
    note: 'Pour days run long — overtime logged separately.',
  },
  Security: {
    in: '06:00',
    out: '14:00',
    hours: 8,
    days: 'All days',
    grace: 5,
    setBy: 'Simran Kaur',
    note: 'Three shifts. This is Shift A.',
  },
  HR: {
    in: '09:30',
    out: '18:30',
    hours: 8,
    days: 'Mon–Sat',
    grace: 15,
    setBy: 'Simran Kaur',
    note: '',
  },
  Admin: {
    in: '10:00',
    out: '19:00',
    hours: 8,
    days: 'Mon–Fri',
    grace: 30,
    setBy: 'Nitish Walia',
    note: '',
  },
  'QA / QC': {
    in: '08:30',
    out: '17:30',
    hours: 8,
    days: 'Mon–Sat',
    grace: 10,
    setBy: 'T. Fernandes',
    note: '',
  },
  Labour: {
    in: '08:00',
    out: '17:00',
    hours: 8,
    days: 'Mon–Sat',
    grace: 0,
    setBy: 'Sharma Contractors',
    note: 'Muster taken at gate, not biometric.',
  },
};

export const SAL_SEED: any = {
  'MB-ADM-0001': {
    basic: 0,
    hra: 0,
    special: 0,
    pf: 0,
    pt: 0,
    note: 'Director — drawings, not payroll',
  },
  'MB-HR-0001': { basic: 42000, hra: 21000, special: 12000, pf: 1800, pt: 200, note: '' },
  'MB-PUR-0012': { basic: 48000, hra: 24000, special: 15000, pf: 1800, pt: 200, note: '' },
  'MB-STR-0004': { basic: 36000, hra: 18000, special: 9000, pf: 1800, pt: 200, note: '' },
  'MB-ACC-0002': { basic: 45000, hra: 22500, special: 13000, pf: 1800, pt: 200, note: '' },
  'MB-MNT-0006': { basic: 32000, hra: 16000, special: 7000, pf: 1800, pt: 200, note: '' },
  'MB-SEC-0007': {
    basic: 16000,
    hra: 6400,
    special: 2600,
    pf: 1800,
    pt: 200,
    note: 'Shift allowance paid separately',
  },
};

export const DEVICE_SEED: any = [
  {
    id: 'DV-201',
    pid: 'MB-PUR-0012',
    type: 'Phone',
    model: 'Samsung M14',
    imei: '352094081234566',
    sim: '+91 98140 00012',
    issued: '14 Mar 2020',
  },
  {
    id: 'DV-202',
    pid: 'MB-STR-0004',
    type: 'Phone',
    model: 'Redmi 12',
    imei: '354876101234560',
    sim: '+91 98140 00040',
    issued: '05 Jun 2020',
  },
  {
    id: 'DV-203',
    pid: 'MB-STR-0004',
    type: 'Scanner',
    model: 'Zebra TC21',
    imei: '351756051234567',
    sim: '—',
    issued: '12 Jan 2024',
  },
  {
    id: 'DV-204',
    pid: 'MB-SEC-0007',
    type: 'Phone',
    model: 'Nokia C12',
    imei: '353012111234561',
    sim: '+91 98140 00071',
    issued: '15 Oct 2022',
  },
  {
    id: 'DV-205',
    pid: 'MB-ACC-0002',
    type: 'Laptop',
    model: 'Lenovo ThinkPad',
    imei: '—',
    sim: '—',
    issued: '20 Aug 2019',
  },
];

export const CONTACT_SEED: any = {
  'MB-HR-0001': {
    phone: '9814000021',
    email: 'simran.kaur88@gmail.com',
    vPhone: true,
    vEmail: true,
  },
  'MB-PUR-0012': {
    phone: '9814000012',
    email: 'rkhanna.pers@gmail.com',
    vPhone: true,
    vEmail: false,
  },
  'MB-STR-0004': { phone: '9814000040', email: 'verma.s@yahoo.in', vPhone: false, vEmail: false },
  'MB-SEC-0007': { phone: '9814000071', email: '', vPhone: false, vEmail: false },
};

export const LEAVE_SEED: any = {
  Purchase: {
    casual: 12,
    sick: 8,
    earned: 15,
    halfDay: 'Under 5h worked counts half.',
    lateAfter: 3,
  },
  Store: { casual: 10, sick: 8, earned: 15, halfDay: 'Under 5h worked counts half.', lateAfter: 3 },
  Maintenance: { casual: 10, sick: 10, earned: 15, halfDay: 'Under 4h counts half.', lateAfter: 4 },
  Accounts: {
    casual: 12,
    sick: 8,
    earned: 18,
    halfDay: 'Under 5h worked counts half.',
    lateAfter: 3,
  },
  'Site Engineering': {
    casual: 10,
    sick: 8,
    earned: 15,
    halfDay: 'Under 5h counts half. Pour days exempt.',
    lateAfter: 4,
  },
  Security: { casual: 8, sick: 8, earned: 12, halfDay: 'Shift is whole or nothing.', lateAfter: 2 },
  HR: { casual: 12, sick: 8, earned: 15, halfDay: 'Under 5h worked counts half.', lateAfter: 3 },
  Admin: { casual: 15, sick: 10, earned: 21, halfDay: '—', lateAfter: 6 },
  'QA / QC': { casual: 10, sick: 8, earned: 15, halfDay: 'Under 5h counts half.', lateAfter: 3 },
  Labour: { casual: 0, sick: 0, earned: 0, halfDay: 'Paid by muster, per day.', lateAfter: 0 },
};
