"""
Build the payload the shareable preview runs on.

Takes the REAL /bootstrap response from a running server and removes what must
not sit at a URL. Starting from the server's own response rather than
reconstructing one means the preview cannot drift out of shape as the payload
grows — a key added to the API appears here automatically.

    TOK=$(curl -s -X POST localhost:4000/api/v1/auth/login \
        -H 'content-type: application/json' \
        -d '{"identifier":"MB-HR-0001","password":"..."}' \
      | python3 -c "import sys,json;print(json.load(sys.stdin)['accessToken'])")
    curl -s -H "authorization: Bearer $TOK" localhost:4000/api/v1/bootstrap -o boot.json
    python3 scripts/import/04-preview.py boot.json

What comes out has the same structure, the same headcount and the same
departments. What it does not have is any regulated identifier: Aadhaar, PAN,
home addresses, full mobile numbers, salaries, device IMEIs, and residents'
names, emails and PANs. They are ABSENT, not masked in the UI — there is nothing to recover by
opening devtools.
"""
import json, re, sys, unicodedata

src = sys.argv[1] if len(sys.argv) > 1 else 'boot.json'
w = json.load(open(src))


def mask_phone(v):
    """Last four digits. Enough to recognise your own, useless to anyone else."""
    d = re.sub(r'\D', '', str(v or ''))
    return f'+91 ..... {d[-4:]}' if len(d) >= 4 else ''


def initials(name):
    n = unicodedata.normalize('NFKC', str(name or '')).strip()
    n = re.sub(r'^(Mr|Mrs|Ms|Dr|Smt|Shri)\.?\s+', '', n, flags=re.I)
    parts = [x for x in n.split() if x]
    if not parts:
        return '—'
    return f'{parts[0][0]}. {parts[-1]}' if len(parts) > 1 else parts[0]


# People keep their name, designation, department, dates and reporting line —
# that is the structure the preview exists to show. Nothing identifying goes.
for p in w.get('people', []):
    for k in ('aadhaar', 'pan', 'address', 'phone', 'email', 'personalEmail', 'kyc'):
        p.pop(k, None)

w['contacts'] = {k: {'phone': mask_phone(v.get('phone')), 'email': ''}
                 for k, v in (w.get('contacts') or {}).items()}

# Salary is behind a role check on the server. It is behind nothing at a URL.
w['salaries'] = {}

# Devices. The model and the type are the point of the screen; an IMEI is a
# permanent handset identifier and a SIM is a phone number, and both sit against
# a named person here.
for d in w.get('devices', []):
    d['imei'] = ''
    d['sim'] = mask_phone(d.get('sim'))

# Residents: the unit, the tower, and an initial. No emails, no PANs, no
# addresses, no full names.
for s in w.get('sales', []):
    s['buyer'] = initials(s.get('buyer'))
    s['phone'] = ''
    s['email'] = ''
    s['address'] = ''
    s.pop('pan', None)

# Company tax numbers are not the preview's business either.
for c in w.get('companies', []):
    c['gstin'] = ''
    c['pan'] = ''
    c['addr'] = ''

# Free text that people type. A note meant for one desk can name a number or an
# address, and this file is a URL — so anything shaped like a phone number or an
# email is redacted here whatever it was written for. Belt and braces: nothing
# generated is supposed to put one in, and this is what catches it when it does.
CONTACT_SHAPED = re.compile(r'[\w.+-]+@[\w-]+\.[\w.]+|(?<!\d)(?:\+?91[\s-]?)?\d{10,}(?!\d)')
def redact(v):
    return CONTACT_SHAPED.sub('[removed]', str(v or ''))

for t in w.get('hrTasks', []):
    t['text'] = redact(t.get('text'))
for a in w.get('hrAnn', []):
    a['title'] = redact(a.get('title'))
    a['body'] = redact(a.get('body'))
for n in w.get('hrLog', []):
    n['what'] = redact(n.get('what'))
for p in w.get('people', []):
    p['growth'] = redact(p.get('growth'))
    for note in p.get('notes', []) or []:
        note['text'] = redact(note.get('text'))

w['me'] = {**w.get('me', {}), 'email': 'preview@marbellagroup.in'}

out = 'apps/web/src/preview/data.ts'
open(out, 'w').write(
    '/**\n'
    ' * The payload the shareable preview runs on.\n'
    ' *\n'
    " * Marbella's real structure, taken from a live /bootstrap response, with every\n"
    ' * regulated identifier removed. A preview is a URL and a URL can be forwarded,\n'
    ' * so Aadhaar numbers, PAN numbers, home addresses, full mobiles, salaries and\n'
    ' * residents\' names are ABSENT from this file rather than hidden by it. There is\n'
    ' * nothing here to recover by opening devtools.\n'
    ' *\n'
    ' * Generated by scripts/import/04-preview.py — do not hand-edit.\n'
    ' */\n\n'
    'export const PREVIEW_WORLD = '
    + json.dumps(w, ensure_ascii=False, separators=(',', ':'))
    + ' as unknown as Record<string, unknown>;\n'
)
print(f'{len(w.get("people", []))} people, {len(w.get("sales", []))} units, {len(w)} keys -> {out}')
